#!/bin/bash

format_err() {
    echo "File '$FILE' isn't formatted correctly." && exit 1
}

git diff --name-only --cached | while read -r FILE; do
    if printf '%s' "$FILE" | grep -q '\.java$'; then
        FILE_RAW="$(git show ":$FILE")"
        FILE_FORMATTED="$(printf '%s' "$FILE_RAW" | uncrustify -l java -c uncrustify.cfg)" || exit 2
        diff <(echo "$FILE_RAW") <(echo "$FILE_FORMATTED") || format_err
    fi
done
